
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxkopqltbmwxrdobaims.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94a29wcWx0Ym13eHJkb2JhaW1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTE2NjEsImV4cCI6MjA2MjI4NzY2MX0.kDQDRqu50p8voYWBl0SkjdDZj_tFrZ2wh92_p4le1JI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
